### ISSUE TITLE
Error compiling in Expo 54

### ISSUE THREAD

**Issue by holmesjr** [jerson/react-native-fast-rsa#96]
I just tried an upgrade to Expo 54. I have  react-native-fast-rsa 2.6.2 in the project.

While it compiles in SDK 53, with v54.0.7 I get the following build errors:

```
C/C++: In file included from node_modules/react-native-fast-rsa/cpp/react-native-fast-rsa.cpp:1:
C/C++: In file included from node_modules/react-native-fast-rsa/cpp/react-native-fast-rsa.h:3:
C/C++: In file included from node_modules/react-native/ReactCommon/jsi/jsi/jsilib.h:10:
C/C++: node_modules/react-native/ReactCommon/jsi/jsi/jsi.h:79:5: error: no matching function for call to 'snprintf'
C/C++:    79 |     std::snprintf(
C/C++:       |     ^~~~~~~~~~~~~
C/C++: /Users/jamesholmes/Library/Android/sdk/ndk/27.1.12297006/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/stdio.h:286:5: note: candidate function not viable: 1st argument ('const value_type *' (aka 'const char *')) would lose const qualifier
C/C++:   286 | int snprintf(char* __BIONIC_COMPLICATED_NULLNESS __buf, size_t __size, const char* _Nonnull __fmt, ...) __printflike(3, 4);
C/C++:       |     ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C/C++: /Users/jamesholmes/Library/Android/sdk/ndk/27.1.12297006/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/bits/fortify/stdio.h:77:5: note: candidate function not viable: 1st argument ('const value_type *' (aka 'const char *')) would lose const qualifier
C/C++:    77 | int snprintf(char* const __BIONIC_COMPLICATED_NULLNESS __pass_object_size dest, size_t size, const char* _Nonnull format, ...)
C/C++:       |     ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C/C++: 1 error generated.
```

**Comment by branikclimbs** [comment]
I encountered the same error when trying to upgrade to Expo SDK 54 today. 

I was able to fix it using this patch. I don't have experience with native development, so I'm not sure if this is the correct solution, but it works for me. I suggest waiting for the official fix for production release purposes or until someone confirms that nothing else is needed 😄 ✌️   

```
diff --git a/android/CMakeLists.txt b/android/CMakeLists.txt
index 17bcf67889a4d36f8ca3bbe0897ca2319d7f6136..a691bb5ce9de537b653e3bb5fd8366218764f005 100644
--- a/android/CMakeLists.txt
+++ b/android/CMakeLists.txt
@@ -1,7 +1,7 @@
 cmake_minimum_required(VERSION 3.9.0)
 
 set (CMAKE_VERBOSE_MAKEFILE ON)
-set (CMAKE_CXX_STANDARD 14)
+set (CMAKE_CXX_STANDARD 17)
 set (BUILD_DIR ${CMAKE_SOURCE_DIR}/build)
 
 add_library(rsa_bridge SHARED IMPORTED)
diff --git a/android/build.gradle b/android/build.gradle
index 288f898a9b44528be82bdd61195897cfaaf3f57a..76ca6b72b703f742833edefbed59f218788ac0b0 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -67,7 +67,7 @@ android {
 
     externalNativeBuild {
       cmake {
-        cppFlags "-O2 -frtti -fexceptions -Wall -Wno-unused-variable -fstack-protector-all"
+        cppFlags "-std=c++17 -O2 -frtti -fexceptions -Wall -Wno-unused-variable -fstack-protector-all"
         abiFilters "x86", "x86_64", "armeabi-v7a", "arm64-v8a"
         arguments "-DNODE_MODULES_DIR=${rootDir}/../node_modules"
       }
diff --git a/android/gradle.properties b/android/gradle.properties
index c72ff44f048d5e06324682d45884624d61a0a91b..49b573314c78ad8aab7f156ab0a70d8779c26a30 100644
--- a/android/gradle.properties
+++ b/android/gradle.properties
@@ -2,4 +2,4 @@ FastRsa_kotlinVersion=1.7.0
 FastRsa_minSdkVersion=21
 FastRsa_targetSdkVersion=33
 FastRsa_compileSdkVersion=33
-FastRsa_ndkversion=28.0.13004108
+FastRsa_ndkversion=28.1.13356709

```

**Comment by acc-amilojkovic** [comment]
I'm getting the exact same error as well when building the App on Expo SDK 54 (It worked on SDK 53). Hopefully soon a new release will come to fix this issue. Thanks for creating the issue i thought i was going insane.

**Comment by tastydev** [comment]
Fixed in PR: https://github.com/jerson/react-native-fast-rsa/pull/97
