### PR TITLE
feat: react native >=0.80, android 16kb paging support

### LINKED ISSUE #96: Error compiling in Expo 54
I just tried an upgrade to Expo 54. I have  react-native-fast-rsa 2.6.2 in the project.

While it compiles in SDK 53, with v54.0.7 I get the following build errors:

```
C/C++: In file included from node_modules/react-native-fast-rsa/cpp/react-native-fast-rsa.cpp:1:
C/C++: In file included from node_modules/react-native-fast-rsa/cpp/react-native-fast-rsa.h:3:
C/C++: In file included from node_modules/react-native/ReactCommon/jsi/jsi/jsilib.h:10:
C/C++: node_modules/react-native/ReactCommon/jsi/jsi/jsi.h:79:5: error: no matching function for call to 'snprintf'
C/C++:    79 |     std::snprintf(
C/C++:       |     ^~~~~~~~~~~~~
C/C++: /Users/jamesholmes/Library/Android/sdk/ndk/27.1.12297006/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/stdio.h:286:5: note: candidate function not viable: 1st argument ('const value_type *' (aka 'const char *')) would lose const qualifier
C/C++:   286 | int snprintf(char* __BIONIC_COMPLICATED_NULLNESS __buf, size_t __size, const char* _Nonnull __fmt, ...) __printflike(3, 4);
C/C++:       |     ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C/C++: /Users/jamesholmes/Library/Android/sdk/ndk/27.1.12297006/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/bits/fortify/stdio.h:77:5: note: candidate function not viable: 1st argument ('const value_type *' (aka 'const char *')) would lose const qualifier
C/C++:    77 | int snprintf(char* const __BIONIC_COMPLICATED_NULLNESS __pass_object_size dest, size_t size, const char* _Nonnull format, ...)
C/C++:       |     ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C/C++: 1 error generated.
```

### PR DESCRIPTION
**Pull request by tastydev**
Hello,

this pr fixes https://github.com/jerson/react-native-fast-rsa/issues/96 and https://github.com/jerson/react-native-fast-rsa/issues/94.

Build errors fixed for RN >=0.80 and also for EXPO SDK 54 by using the c++17 standard now as it aligns better with the current NDK toolchain.

Android 16KB paging is supported now. Root RN still compiles with NDK 27 which needs `-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON`  to be set as mentioned inside the docs: https://developer.android.com/guide/practices/page-sizes#compile-r27

**Paging support before:**
47cff490a8ad444b4906e452aa91a022

**Paging support after:**
50554b455d81ddd19e1c7c6e13c6cf7d

## Summary by CodeRabbit

* **Chores**
  * Updated Android build configuration to support flexible page sizes, improving compatibility and potential memory efficiency on newer devices.
  * Upgraded native compilation standard to C++17 to enhance stability, performance, and future compatibility across Android builds.

### CODE REVIEW

**Review by jerson — APPROVED** [review]

**Comment by jerson** [comment]
@tastydev Thank You for this
